import sys
import os

# Ensure the agents directory is in the Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "agents")))

from Tools import AgentTools, SaveDocumentRequest

def main():
    print("Initializing AgentTools (this may take a moment to load models/indexes)...")
    tools = AgentTools()
    
    # Let's test the rich markdown formatting
    markdown_content = """
# SAP Integration Report

## 1. Overview
This is a test report generated by the **WeasyPrint** HTML-to-PDF pipeline inside our Agentic System.

### 1.1 Highlights
* The pipeline supports **bold text**, *italics*, and lists.
* It cleanly renders markdown tables.
* It supports fenced code blocks.

## 2. System Status

| Module | Status | Uptime | Notes |
|--------|--------|--------|-------|
| FI-CO  | Active | 99.9%  | Normal operation |
| MM     | Active | 99.8%  | Pending material sync |
| SD     | Down   | 85.0%  | Investigating routing error |

## 3. Implementation Code
Here is an example of the Python code used to query the system:

```python
def check_module_status(module_name: str) -> str:
    \"\"\"Queries SAP for module status.\"\"\"
    if module_name == "SD":
        return "Down"
    return "Active"
```

> **Note**: This document was generated automatically by the `write_file` tool.
"""
    
    request = SaveDocumentRequest(
        filename="test_report.pdf",
        data=markdown_content
    )
    
    print("\nCalling write_file to generate 'test_report.pdf'...")
    result = tools.write_file(request)
    print("\nResult:")
    print(result)

if __name__ == "__main__":
    main()
